### PR TITLE
Rust 2018 fixes

### PR DESCRIPTION
**Pull request by XVilka**

### CODE REVIEW

**Comment by chinmaydd** [comment]
Interesting why that should fail (and only on beta nonetheless)

**Comment by XVilka** [comment]
@chinmaydd most likely Travis own problems:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```
Try to rerun it.

**Comment by chinmaydd** [comment]
Seems like that was the problem. PR looks good to me. I can merge it unless you are waiting on @sushant94's review ?

**Comment by XVilka** [comment]
@chinmaydd please do merge, yes.

**Pull request merged**
